Feature/geoquiz chapter3
agustinaGallo97/GithubRepository pull request #4
Opened 2019-11-22 21:00 UTC by agustinaGallo97

## :link: Jira Tracker reference:
*[AP - Chapter 3] The Activity Lifecycle - https://androidtraining.atlassian.net/browse/AT-40

## Description:
I've done chapter 3 and also both challenges.

## :camera_flash: UI preview
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/33355750/69460046-e85ad380-0d51-11ea-8058-389ceca970e6.gif)

## :pushpin: Notes:
Both challenges are included.

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/AndroidManifest.xml
> +        <activity android:name=".Views.QuizActivity">
use lowercase for packages

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Controllers/QuestionController.java
> +    questionBank = new ArrayList<Question>();
you can use `Arrays.asList(`

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Controllers/QuestionController.java
> +  private List<Question> questionBank;
this should be `final` and `@NonNull`

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Controllers/QuestionController.java
> +  public static QuestionController getInstance() {
Nullability

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Controllers/QuestionController.java
> +  public List<Question> getQuestionBank() {
Nullability

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Views/QuizActivity.java
> +  private HashSet<Question> resolvedQuestions = new HashSet();
I think you can define it as set
```suggestion
  private Set<Question> resolvedQuestions = new HashSet();
```

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Views/QuizActivity.java
> +        countOfCorrectQuestionsResolved += 1;
the method name is `showToastCorrectly` but you are doing a lot of thing. Please, split it in multiple methods

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Views/QuizActivity.java
> +  private void disableButtons(boolean value) {
the param name is not good (it should be representative)

2019-11-22 22:15 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/Views/QuizActivity.java
> +  private void disableButtons(boolean value) {
Also we try to add positive names in methods, maybe you can change `disableButtons` to `enableButtons`. However, I think `setButtonsState` is better

2019-11-24 13:37 UTC, mirland approved these changes

2019-11-24 13:37 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/controllers/QuestionController.java
> +  private List<Question> questionBank;
Nullability

2019-11-24 13:37 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/views/QuizActivity.java
> +  private Set<Question> resolvedQuestions = new HashSet();
nullability and final

2019-11-24 13:37 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/views/QuizActivity.java
>      }
you can make it shorter

2019-11-24 13:37 UTC, matir91 commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/views/QuizActivity.java
> +  private void setButtonsState(boolean value) {
change the param name, maybe `enabled`?

2019-11-24 19:56 UTC, FerrariBruno approved these changes

2019-11-24 19:56 UTC, FerrariBruno commented on GeoQuizChallenge/app/src/main/java/com/bignerdranch/android/geoquiz/views/QuizActivity.java
> +  private void updateResolvedQuestions(Question actualQuestion) {
nullability

2019-11-25 16:13 UTC, FerrariBruno requested changes
It's missing Timber! Look at the card's description: https://androidtraining.atlassian.net/browse/AT-40

2019-11-26 18:42 UTC, FerrariBruno approved these changes

2019-11-26 18:47 UTC, merged